### ISSUE TITLE
Issue with Leaflet 0.6.4

### ISSUE THREAD

**Issue by mroadman** [smeijer/L.GeoSearch#30]
When I tried to use the code with the new Leaflet (0.6.4), it would return an error saying: XMLHttpRequest cannot load http://dev.virtualearth/net/REST/v1/Locations?query.... Origin is not allowed by Access-Control-Allow-Origin."

I changed the Leaflet version to 0.4.4, and it worked fine, but I have to use 0.6.4 per company standards. Any suggestions?

**Comment by smeijer** [comment]
New version should have a working bing provider again.
