### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by reubano** [smeijer/L.GeoSearch#34]
Please add this as a [bower component](http://bower.io/).

**Comment by althaus** [comment]
:+1:

**Comment by smeijer** [comment]
#37 should fix this. But I'm unfamiliar with bower, and I cannot find L.GeoSearch on http://bower.io/search/ like @flakron is saying.

Can one of you help me out?

**Comment by althaus** [comment]
@smeijer It doesn't look like it was properly registered.

**Comment by smeijer** [comment]
@althaus, thanks. I've seem to have fixed this one. Can you confirm?

```cmd
bower install leaflet-geosearch
```
