### ISSUE TITLE
How to perform search after provider is initialized?

### ISSUE THREAD

**Issue by notionslate** [smeijer/L.GeoSearch#35]
I am trying to use the geosearch during my map initialization. After adding the geosearch control to the map, I programmatically  enter an address and kick off a search. The problem is that the search is executed before the onLoadGoogleApiCallback occurs and so there is an error because the L.GeoSearch.Provider.Google.Geocoder is undefined.  How or when is the proper time to kick off a geosearch so that I know the provider is completely loaded and ready?

**Comment by Polymathronic** [comment]
I also end up with an undefined geocoder (L.GeoSearch.Provider.Google.Geocoder), when I try the "custom GeoSearch control" example (map already initialized).

**Comment by DevanB** [comment]
Has any progress been made on this? I am receiving the `undefined geocoder` error also.

**Comment by smeijer** [comment]
This issue is fixed trough #57. All queries passed to the control are being queued until the `Google API` is loaded. Once loaded, the queries are all being processed. All and not only the latest! This so to be sure that also all callbacks one can bind to a search action, are being called.
