### ISSUE TITLE
Preserve appropriate zoom level for search

### ISSUE THREAD

**Issue by brianherbert** [smeijer/L.GeoSearch#4]
Just a feature request, it would be nice if geosearch could get the accuracy of the search and zoom to the appropriate level if the geolocator returns that data. For example, if I search for a city name, it should show the city and not a street at the center.

Awesome work!

**Comment by smeijer** [comment]
Current version should do just that. Although, the provider being used have to support this. The `Google` provider (for example) does.

Thanks for the request.
