### ISSUE TITLE
Google Geosearch

### ISSUE THREAD

**Issue by mblais29** [smeijer/L.GeoSearch#44]
Doesn't work, a marker gets placed in the center of the map when I search for a place. The ESRI and the other ones work fine. Do I need an API key for google?

**Comment by smeijer** [comment]
Do you have an example of what you mean? Google works fine here. Only Bing, and Nokia seems to require an API key.

**Comment by hilarykitz** [comment]
Setting bounds isn't working for me, and getLocations with Google is pinning to American versions of European city names (Amsterdam NY , Naples Florida, e.g.)

My initialization is: 
var cityLocGetter = new L.Control.GeoSearch({
    provider: new L.GeoSearch.Provider.Google({bounds: 35.084380|-11.333104|70.211940|51.163554})
}).addTo(map);

and the function passed is 
function fly(thisCity, thisRoute, rURL) {
    if (shownCities.thisCity) {}
    else { 
      var city = thisCity; 
      var googleGeocodeProvider = new L.GeoSearch.Provider.Google(), addressText = thisCity;
        googleGeocodeProvider.GetLocations( addressText, function ( data ) {
            var lat = data[0].X;
            var lng = data[0].Y;
            var latlng = [lng, lat];
            var marker = new L.Marker(latlng, {icon: icon}); 
            marker.addTo(map);
            map.setView( latlng, 7, {animate:true, duration:0.75, noMoveStart:true, easeLinearity: 0.05});
        });//geocoder
    }//else
};

if I change the function to 
var googleGeocodeProvider = new L.GeoSearch.Provider.Google({bounds: 35.084380|-11.333104|70.211940|51.163554}),  [...] 

I get 'InvalidValueError: in property bounds: not a LatLngBounds or LatLngBoundsLiteral: not an Object'
How to I pass bounds correctly?

**Comment by smeijer** [comment]
Passing data to a provider, is always according to official documentation. In this case according to [Google Maps API docs](https://developers.google.com/maps/documentation/javascript/reference).

The correct way to provide a bounds is:
```javascript
var provider = new L.GeoSearch.Provider.Google({
  bounds: { north: 54.303704, east: 9.722900, south: 49.830896, west: 0.867919 }
});

provider.GetLocations( 'Amsterdam', function ( data ) {
  console.log(data);
});
```

See the following docs for the what and why: [Geocoder](https://developers.google.com/maps/documentation/javascript/reference#Geocoder) and [LatLngBoundsLiteral](https://developers.google.com/maps/documentation/javascript/reference#LatLngBoundsLiteral) for more details on your problem.
