### ISSUE TITLE
pass geocode directly to leaflet map .setView() and .marker()

### ISSUE THREAD

**Issue by drkhannah** [smeijer/L.GeoSearch#46]
I have an address that is coming from a populated object

I just want to geocode the address, then pass that to the leaflet map .setView() and .marker()

how do i do this

here is my code currently

            var mapStreetAddress = viewModel.get("selectedProperty.streetAddress"),
                mapCity = viewModel.get("selectedProperty.city"),
                mapState = viewModel.get("selectedProperty.state"),
                mapCountry = viewModel.get("selectedProperty.country"),
                mapZipCode = viewModel.get("selectedProperty.zipCode"),
                geoCode = new L.Control.GeoSearch(mapStreetAddress + mapCity + ',' + mapState +  mapCountry + mapZipCode);

            var map = L.map('map',{
                zoomControl: false,
                dragging: false,
                touchZoom: false,
                scrollWheelZoom: false,
                doubleClickZoom : false,
                boxZoom: false,
                tap: false,
                closePopupOnClick: false
            }).setView(geoCode, 18);
            L.tileLayer('http://{s}.tiles.mapbox.com/v3/drkhannah.jn9benmp/{z}/{x}/{y}.png', {
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
            }).addTo(map);
            var marker = L.marker(geoCode).addTo(map);

**Comment by smeijer** [comment]
Direct use of the provider is currently only supported in the `Google Provider`.

Usage is then like:
```javascript
var provider = new L.GeoSearch.Provider.Google();

provider.GetLocations( 'Amsterdam', function (data) {
  console.log(data);
});
```
