### ISSUE TITLE
German umlauts may not work due to encoding issues with OSM

### ISSUE THREAD

**Issue by janLo** [smeijer/L.GeoSearch#47]
We use parts of the geosearch code for placing a marker on a leaflet map. If you use a browser on some windows systems and input a address containing umlauts like "ä" or "ü" then you will get a 400 response from OSM. This can be fixed by encoding the query before passing it to L.Util.getParamString().

We have done this at https://github.com/smeijer/L.GeoSearch/blob/master/src/js/l.geosearch.provider.openstreetmap.js#L22-23

The commit in our project was: eXma/meet-and-eat-registration-system@2067b0a0a0cafdbd56438d0c9ead308cca5789d8

**Comment by valioDOTch** [comment]
+1

**Comment by smeijer** [comment]
Time seem to have fixed this issue. `L.Util.getParamString` does the encoding now.
