### ISSUE TITLE
When search is used on more than one map, it doesn't work

### ISSUE THREAD

**Issue by brianherbert** [smeijer/L.GeoSearch#5]
I have two maps loaded, both using this plugin. When I perform a search from the second map, it doesn't actually pass the query text to the geolocator. ie: http://nominatim.openstreetmap.org/search?q=&format=json

My guess is it's pulling the value of the first address input and not the second one.

**Comment by smeijer** [comment]
This one is not relevant anymore. Fixed by #50 among others.
