### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by fredrikekelund** [smeijer/L.GeoSearch#56]
I see that this repo already has a package.json, but it's not published to npm. Aside from maybe bumping the version, it seems it'd be just a matter of running `npm publish`, would be great to be able to access the library from there!

**Comment by smeijer** [comment]
I'll take a look at this in the near future. I've planned to do some refactoring in a couple of weeks. I guess publishing after that is a great idea. Thanks for the suggestion.

**Comment by ludoo0d0a** [comment]
I wait this push to npm repo too.
And AMD/requireJs/commonJS support too ;)

**Comment by raphael-boucher** [comment]
Yes, me too, in order to use it with browserify!

**Comment by Mithgol** [comment]
This comment is left here to add this issue to my https://github.com/notifications/participating list.

(I could silently hit “Subscribe”, but then that would appear on https://github.com/notifications only.)

**Comment by smeijer** [comment]
Finally done: 

https://www.npmjs.com/package/leaflet-geosearch

Thanks all!
