### ISSUE TITLE
Direct use of Provider doesn't work

### ISSUE THREAD

**Issue by codeofsumit** [smeijer/L.GeoSearch#57]
This

```
var googleGeocodeProvider = new L.GeoSearch.Provider.Google(),
  addressText = 'Amsterdam';

googleGeocodeProvider.GetLocations( addressText, function ( data ) {
  // in data are your results with x, y, label and bounds (currently availabel for google maps provider only)
});
```

causes an error: `Cannot read property 'geocode' of undefined
    at L.GeoSearch.Provider.Google.L.Class.extend.GetLocations`.

**Comment by roloyar** [comment]
Same for me. Really waiting for a solution.

**Comment by garfiaslopez** [comment]
Someone have the solution to this? .. :( Same for me, Is not working....

**Comment by Savitha-N** [comment]
I am also getting same issue. Why this error comes??

**Comment by ayupdigital** [comment]
It looks like upon calling ``new L.GeoSearch.Provider.Google()`` the module dynamically loads the Google Maps API via an internal function called ``loadMapsApi``.

The ```geocoder.geocode(parameters...``` function only exists once the Google Maps API script is fully loaded and the callback (```onLoadGoogleApiCallback```) has been executed. This is why the ```undefined 'geocode'``` error is being thrown. Fundamentally the Google Maps API is being loaded asynchronously but the provider module doesn't take this into consideration when referencing functions.

As a temporary stop-gap solution, load the Google Maps API before loading the L.GeoSearch plugin. E.g. in your template:

```<script src="https://maps.googleapis.com/maps/api/js?v=3&callback=&sensor=false"></script>```

You'll have to modify the ```l.geosearch.provider.google.js``` file and comment out line 19 and line 20:

``` 
// if (!window.google || !window.google.maps)
//          this.loadMapsApi();
```

and add the following below:

```L.GeoSearch.Provider.Google.Geocoder = new google.maps.Geocoder();```

Hopefully this will help someone until a fix has been issued.

**Comment by hilarykitz** [comment]
How can I pass parameters like region limits to the Google geocoder in this format?

**Comment by smeijer** [comment]
Direct use of the Google provider is now supported in the `develop` branch. Thanks @ayupdigital for the detailed explanation.

Usage like:
```javascript
var googleGeocodeProvider = new L.GeoSearch.Provider.Google();

googleGeocodeProvider.GetLocations( 'Amsterdam', function ( data ) {
  console.log(data);
});
```

All calls to `GetLocations` are being re-invoked once the Google API is ready. This is to be sure that all callbacks are being triggered. 

It will be merged to `master` soon.
