### ISSUE TITLE
Event after finding a location

### ISSUE THREAD

**Issue by MeMyselfI** [smeijer/L.GeoSearch#60]
Is there an event I can listen too when an address is found and the map is centered accordingly?

**Comment by mbarrenecheajr** [comment]
+1 this feature request..

**Comment by smeijer** [comment]
There is:

```
map.on('geosearch_showlocation', (result) => {
 console.log(result); // location + marker
});
```

**Comment by SalahAdDin** [comment]
> There is:
> 
> ```js
> map.on('geosearch_showlocation', (result) => {
>  console.log(result); // location + marker
> });
> ```

There is a problem with it: it is called many times.
