### ISSUE TITLE
Map does not work anymore

### ISSUE THREAD

**Issue by leolux** [smeijer/L.GeoSearch#62]
No map is shown at http://smeijer.github.io/GeoSearch/ anymore, what could be the cause?

**Comment by asymmetric** [comment]
FWIW, the call to `cloudmade.com` returns a `403`.

**Comment by penproductions** [comment]
I get this error when trying to load the example using OpenStreetMap. This is the default example. I can get the example to work when using Google. 

`l.control.geosearch.js:153 XMLHttpRequest cannot load file://nominatim.openstreetmap.org/search?q=12%20galloway%20cres%20ontario&format=json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.L.Control.GeoSearch.L.Control.extend.sendRequest @ l.control.geosearch.js:153L.Control.GeoSearch.L.Control.extend.geosearch @ l.control.geosearch.js:103L.Control.GeoSearch.L.Control.extend._onKeyUp @ l.control.geosearch.js:233t.(anonymous function).a @ leaflet.js:7`

**Comment by Mithgol** [comment]
FWIW, the body of a 403 page ([example](http://c.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/997/256/12/2117/1332.png)) says “Forbidden, wrong apikey”.

**Comment by smeijer** [comment]
Duplicate with #41
