### ISSUE TITLE
_isReady not set to true when google is already loaded

### ISSUE THREAD

**Issue by Golovior** [smeijer/L.GeoSearch#73]
When using google as search and for tiles, the _isReady is not set to true and no searches are performed.  
I solved this by adding `this._isReady = true;` after `onLoadGoogleApiCallback();` in the initialize function.

**Comment by smeijer** [comment]
Fixed this in the `next` branch. Release `v2.0.0` be released before the end of this year. Currently usable trough:

```sh
npm install leaflet-geosearch@next --save
```
