### ISSUE TITLE
Need option to provide google api key

### ISSUE THREAD

**Issue by bkdotcom** [smeijer/L.GeoSearch#77]
It seems to work without it, but google does throw a warning in the console about missing key

**Comment by bkdotcom** [comment]
### [Google Announcement](http://googlegeodevelopers.blogspot.com/2016/06/building-for-scale-updates-to-google.html?utm_source=email&utm_medium=social&utm_campaign=2016-geo-na-website-gmedia-blogs-us-blogPost&utm_content=TBC)

As of June 22, 2016 we are making the following changes to the Google Maps APIs Standard Plan:

1)    We no longer support keyless access (any request that doesn't include an API key). Future product updates are only available for [requests made with an API key](https://developers.google.com/maps/documentation/javascript/get-api-key?utm_source=geoblog&utm_medium=social&utm_campaign=2016-geo-na-website-gmedia-blogs-us-blogPost&utm_content=TBC). API keys allow us to contact developers when required and help us identify misbehaving implementations   
**&hellip;**

**Comment by JackDougherty** [comment]
+1

**Comment by joshdickerson92** [comment]
Has there been any update to the plugin for this or can the API key simply be added in?

**Comment by TheSystem** [comment]
+1

**Comment by joshdickerson92** [comment]
If you follow the link by @bkdotcom to gain a API Key. Then in `l.geosearch.provider.google.js` include the API Key in the following line then it seems to work for me. 

        `var url = "https://maps.googleapis.com/maps/api/js?key=_KEYHERE_&callback=onLoadGoogleApiCallback&sensor=false";`

**Comment by TheSystem** [comment]
I know that, but everytime someone on my team uses a package manager like bower or npm to install or update the components used in the project, needs to remember to go to that file and insert the api key, or the it will break the project....

**Comment by meterlongcat** [comment]
+1

**Comment by dkobia** [comment]
Created a pull request for this so that you can initialize it with:

```javascript
new L.Control.GeoSearch({
  provider: new L.GeoSearch.Provider.Google({
    key: 'YOUR_API_KEY'
  })
}).addTo(map);  
```

**Comment by smeijer** [comment]
Thanks @dkobia , PR is merged.

**Comment by bcalik** [comment]
I get unknown property key error when I try to use it with custom control like:
```js
var googleGeocodeProvider = new L.GeoSearch.Provider.Google({key: '...'});
```

**Comment by dkobia** [comment]
@bcalik ... Will test and push a fix.

**Comment by jb2b38** [comment]
I have the same issue as @bcalik , anything new on the issue?

**Comment by vincent-ollivier-everysens** [comment]
It's because `this.options` is add to `parameters` sent to Google Geocode script ... But "key" is **NOT** a parameter, it should only be on URL. 
```
var parameters = L.Util.extend({
      address: qry
    }, this.options); 
```
