### ISSUE TITLE
Restrict results to a country

### ISSUE THREAD

**Issue by joshdickerson92** [smeijer/L.GeoSearch#81]
I have been trying to restrict the results of a search to the UK using the Google API and changing the URL to include an address and [component filtering](https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering), however this doesn't appear to work, is there a better way of doing this?

**Comment by joshdickerson92** [comment]
Okay, after a bit of further reading, it seems the component filter should be applied to the parameters which seems to work perfectly.

```
    var parameters = L.Util.extend({
            address: qry,
            componentRestrictions: {
                country: 'UK'
            }
        }, this.options);
```

**Comment by mauriau** [comment]
Hi @joshdickerson92
Do you know if we can use multiple coutry code if it's limited to one?
I'm french and I need to include the DOM-TOM (others french territories) and they dont have the same coutry code as France métropolitaine.
Seem like : 
```
  components: 'country:FR,TF,GF,PF,MF,P,RE,GPM',
```
or something else ?
Thanks.
