### ISSUE TITLE
Bounding box for search

### ISSUE THREAD

**Issue by alexgleith** [smeijer/L.GeoSearch#9]
I modified your code a little bit to hack in a bounding box for the Google geocoding.

I'm not sure how to submit a change thingy, so please let me know if there's a better way to do this. 

So, in the file 'l.geosearch.provider.google.js' I modified the start of the getlocations function:

GetLocations: function(qry, callback) {
        var geocoder = L.GeoSearch.Provider.Google.Geocoder;
        var bounds = new google.maps.LatLngBounds(
            new google.maps.LatLng(-42.9063,147.1335),
            new google.maps.LatLng(-42.7167, 147.3444));

        var parameters = L.Util.extend({
            address: qry,
            bounds: bounds
        }, this.options);

This works perfectly. But it's hardcoded, so it would be great to handle it better. (I'm not so good with Javascript  yet and don't know how to do it better...)

**Comment by smeijer** [comment]
The google provider currently takes care of this. I'll take a look at the other providers soon.

**Comment by smeijer** [comment]
No adjustment to providers are needed. They take care of this if the API on the backend is supporting it.
